---
# PLAY PARA CONFIGURACAO DA WORKSPACE
- hosts: workspace
  name: Configurando a Workspace
  remote_user: vagrant
  become: yes
  tasks:
    - name: Ajustando Timezone
      timezone:
        name: America/Sao_Paulo

    - name: Adicionando Key do Repositorio do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionando o Repositório do Docker
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        update_cache: yes

    - name: Instalação do GCLOUD, Terraform, Docker e outras dependências
      apt:
        pkg: ['docker-ce', 'npm' ]
        state: present

    - name: Adicionar Usuario Vagrant no Grupo Docker
      user:
        name: vagrant
        comment: Vagrant User
        groups: docker
