# Nome do Workflow
name: Hacka-G11-Front Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: Set Backend URL
          run: sed -i "s/BACKEND_URL/${{ secrets.BACKEND_URL }}/g" ./src/App.js

        - name: Docker Login
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          run: | 
            echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
            cat key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev/
        - name: Build Image & Push
          env: 
            ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
          run: | 
            docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-frontend:latest .
            docker push ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-frontend:latest

    Deploy:
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: 'Deploy to Cloud Run'
          uses: 'google-github-actions/deploy-cloudrun@v0'
          with:
            image: '${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-frontend:latest'
            service: 'spotmusic-frontend'
